spring:
  flyway:
    validate-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  sql:
    init:
      mode: never

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    com.mrsdeores: INFO
    org.springframework: INFO
    org.hibernate: INFO

app:
  cors:
    allowed-origins: ${FRONTEND_URL}
